---
name: Build with Gradle 7.x

on:
  pull_request:
  workflow_dispatch:

permissions: {}

concurrency:
  group: build-gradle7-${{ github.ref }}
  cancel-in-progress: true

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - uses: actions/setup-java@b6effb05e454b25005698d916606bdc6ffcbf961 # v5.7.0
        with:
          distribution: temurin
          java-version: 11

      - name: Setup hub gradle version
        uses: gradle/actions/setup-gradle@9c971963bec38e04b3d30dcc455b5382be2fdbfb # v6.3.0
        with:
          cache-provider: basic
          gradle-version: 7.4 # https://github.com/runelite/plugin-hub/blob/master/package/gradle/wrapper/gradle-wrapper.properties

      - name: Build plugin using hub gradle version
        run: ./gradlew shadowJar --exclude-task test # tests are already executed by primary gradle task
