---
name: Lint

on:
  push:
    branches:
      - master
  pull_request:

permissions: {}

concurrency:
  group: lint-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - name: Check formatting with Prettier
        uses: actionsx/prettier@3d9f7c3fa44c9cb819e68292a328d7f4384be206
        with:
          # prettier CLI arguments.
          args: --write .
      - name: Show diff
        run: git --no-pager diff --exit-code --color=never
        shell: bash
